
[build]
  command = "npm run build" 
  publish = "/build-output" 
  base = "/"

[[redirects]]  # Configure redirects for client-side routing in SPAs
  from = "/*"
  to = "/index.html"
  status = 200
